from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import List

os.environ.setdefault("PANDAS_NO_USE_NUMEXPR", "1")
os.environ.setdefault("PANDAS_NO_USE_BOTTLENECK", "1")
sys.modules.setdefault("numexpr", None)
sys.modules.setdefault("bottleneck", None)

import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from attribute_extractor import deduplicate_rows, discover_pairs, extract_attributes, load_entities, read_text, save_rows  # noqa: E402


def build_default_paths(script_path: Path) -> tuple[Path, Path, Path, Path]:
    project_root = script_path.parent.parent
    raw_dir = project_root / "原始文本"
    entity_dir = project_root / "实体消歧" / "实体消歧结果"
    relation_attr_path = project_root / "关系消歧" / "关系消歧结果" / "relation_attribute_candidates.csv"
    output_dir = script_path.parent / "属性抽取结果"
    return raw_dir, entity_dir, relation_attr_path, output_dir


def parse_args() -> argparse.Namespace:
    script_path = Path(__file__).resolve()
    default_raw, default_entity, default_relation_attr, default_output = build_default_paths(script_path)
    parser = argparse.ArgumentParser(description="Extract entity attributes from raw text and relation fallback candidates.")
    parser.add_argument("--raw-dir", type=Path, default=default_raw, help="Directory of raw txt files.")
    parser.add_argument("--entity-dir", type=Path, default=default_entity, help="Directory of disambiguated entity csv files.")
    parser.add_argument("--relation-attribute-path", type=Path, default=default_relation_attr, help="CSV path generated by relation disambiguation.")
    parser.add_argument("--output-dir", type=Path, default=default_output, help="Directory of extracted attribute csv files.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    pairs = discover_pairs(args.raw_dir, args.entity_dir)
    if not pairs:
        print("No paired raw/entity files were found.")
        return

    fallback_df = None
    if args.relation_attribute_path.exists():
        fallback_df = pd.read_csv(args.relation_attribute_path, encoding="utf-8-sig")

    all_rows: List[dict] = []
    for raw_path, entity_path in pairs:
        text = read_text(raw_path)
        entities = load_entities(entity_path)
        rows = extract_attributes(text, entities, raw_path.name)
        if fallback_df is not None and not fallback_df.empty:
            extra_rows = fallback_df[fallback_df["source_file"] == raw_path.name].to_dict(orient="records")
            rows = deduplicate_rows([*rows, *extra_rows])
        all_rows.extend(rows)
        save_rows(rows, args.output_dir / f"{raw_path.stem}.csv")
        print(f"[done] {raw_path.stem}: entities={len(entities)}, attributes={len(rows)}")

    merged_rows = deduplicate_rows(all_rows)
    save_rows(merged_rows, args.output_dir / "all_attributes.csv")
    print(f"Processed {len(pairs)} files. attributes={len(merged_rows)}, output_dir={args.output_dir}")


if __name__ == "__main__":
    main()
